inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - spec/**/*

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/IndentationWidth:
  IgnoredPatterns:
    - '^\s*module'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false
